services:
  - type: web
    name: rideconnect-api
    runtime: docker
    plan: free
    dockerfilePath: ./dockerfile
    dockerContext: .
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_URL
        value: https://rideconnect-emp0.onrender.com
      - key: APP_DEBUG
        value: false