[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid

[program:laravel-web]
command=/bin/sh /var/www/scripts/start-web.sh
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/web.log
stderr_logfile=/var/www/storage/logs/web-error.log

[program:php-fpm]
command=php-fpm
autostart=true
autorestart=true

[program:laravel-worker]
command=/bin/sh /var/www/scripts/start-worker.sh
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/worker.log
stderr_logfile=/var/www/storage/logs/worker-error.log

[program:laravel-scheduler]
command=/bin/sh /var/www/scripts/start-scheduler.sh
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/scheduler.log
stderr_logfile=/var/www/storage/logs/scheduler-error.log