[unix_http_server]
file=/tmp/supervisor.sock
chmod=0700

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[supervisord]
nodaemon=true
pidfile=/tmp/supervisord.pid
logfile=/var/www/storage/logs/supervisord.log
logfile_maxbytes=50MB
logfile_backups=3
loglevel=info

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/php-fpm.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
stderr_logfile=/var/www/storage/logs/php-fpm-error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=3

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stdout_logfile=/var/www/storage/logs/nginx.log
stdout_logfile_maxbytes=50MB
stdout_logfile_backups=3
stderr_logfile=/var/www/storage/logs/nginx-error.log
stderr_logfile_maxbytes=50MB
stderr_logfile_backups=3