<x-filament-panels::page>
    <div class="space-y-6" wire:poll.30s>
        <!-- Hero Section -->
        <section class="rounded-xl border-0 bg-gradient-to-r from-indigo-600 to-blue-600 p-6 text-white shadow-lg">
            <p class="text-xs font-semibold uppercase tracking-wider text-indigo-100">AI & Analytics</p>
            <h1 class="mt-1 text-2xl font-semibold sm:text-3xl">AI Insights</h1>
            <p class="mt-2 max-w-2xl text-sm text-indigo-100 sm:text-base">
                AI-powered analytics for demand forecasting, peak hours, and operational optimization.
            </p>
        </section>

        <!-- Key Metrics -->
        <section class="grid grid-cols-1 gap-4 md:grid-cols-2">
            <x-dashboard-card title="Avg Wait Time" :value="$avgWaitTime . ' min'" subtitle="Platform average" tone="blue" />
            <x-dashboard-card title="Acceptance Rate" :value="$acceptanceRate . '%'" subtitle="Driver acceptance" tone="green" />
        </section>

        <!-- Demand by Area -->
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="text-base font-semibold text-slate-900">📍 Demand Heatmap</h2>
            <p class="mt-1 text-xs text-slate-600">Current demand by service area with available driver supply.</p>
            <div class="mt-4 space-y-2">
                @forelse ($demandByArea as $area)
                    <div class="flex items-center gap-3">
                        <div class="min-w-24 text-sm font-medium text-slate-700">{{ $area['area'] }}</div>
                        <div class="flex-1">
                            <div class="h-6 bg-slate-100 rounded-lg overflow-hidden">
                                <div class="h-full bg-gradient-to-r from-blue-400 to-blue-600" style="width: {{ min(100, ($area['demand'] / 500) * 100) }}%"></div>
                            </div>
                        </div>
                        <div class="text-right">
                            <div class="text-sm font-semibold text-slate-900">{{ $area['demand'] }} requests</div>
                            <div class="text-xs text-slate-600">{{ $area['available_drivers'] }} drivers</div>
                        </div>
                    </div>
                @empty
                    <p class="text-sm text-slate-500 text-center py-4">No demand data available.</p>
                @endforelse
            </div>
        </section>

        <!-- Peak Hours -->
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="text-base font-semibold text-slate-900">⏰ Today's Peak Hours</h2>
            <p class="mt-1 text-xs text-slate-600">Expected surge times and demand levels.</p>
            <div class="mt-4 grid grid-cols-1 md:grid-cols-2 gap-3">
                @forelse ($peakHours as $peak)
                    <div class="rounded-lg border-2 @if ($peak['color'] === 'red') border-red-200 bg-red-50 @elseif ($peak['color'] === 'orange') border-orange-200 bg-orange-50 @else border-yellow-200 bg-yellow-50 @endif p-4">
                        <div class="font-semibold @if ($peak['color'] === 'red') text-red-900 @elseif ($peak['color'] === 'orange') text-orange-900 @else text-yellow-900 @endif">
                            {{ $peak['hour'] }}
                        </div>
                        <div class="text-xs @if ($peak['color'] === 'red') text-red-700 @elseif ($peak['color'] === 'orange') text-orange-700 @else text-yellow-700 @endif font-medium mt-1">
                            {{ ucfirst($peak['demand']) }} Demand
                        </div>
                    </div>
                @empty
                    <p class="text-sm text-slate-500 col-span-2 text-center py-4">No peak hour data.</p>
                @endforelse
            </div>
        </section>

        <!-- Weekly Trend -->
        <section class="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
            <h2 class="text-base font-semibold text-slate-900">📊 Weekly Trend</h2>
            <p class="mt-1 text-xs text-slate-600">Rides completed and revenue generated by day.</p>
            <div class="mt-4 overflow-x-auto">
                <table class="w-full text-sm">
                    <thead>
                        <tr class="border-b border-slate-200 text-left text-xs uppercase tracking-wide text-slate-500 font-semibold">
                            <th class="py-2 pr-3">Day</th>
                            <th class="py-2 pr-3">Rides</th>
                            <th class="py-2">Revenue</th>
                        </tr>
                    </thead>
                    <tbody>
                        @forelse ($trendData as $day)
                            <tr class="border-b border-slate-100">
                                <td class="py-2 pr-3 font-medium text-slate-900">{{ $day['date'] }}</td>
                                <td class="py-2 pr-3">
                                    <span class="inline-flex items-center gap-1">
                                        <div class="h-1 bg-blue-400 rounded-full" style="width: {{ ($day['rides'] / 500) * 40 }}px"></div>
                                        {{ $day['rides'] }}
                                    </span>
                                </td>
                                <td class="py-2 font-semibold text-slate-900">${{ number_format($day['revenue'], 2) }}</td>
                            </tr>
                        @empty
                            <tr>
                                <td colspan="3" class="py-4 text-center text-slate-500 text-sm">No trend data.</td>
                            </tr>
                        @endforelse
                    </tbody>
                </table>
            </div>
        </section>

        <!-- Recommendations -->
        <section class="rounded-xl border border-green-200 bg-green-50 p-4">
            <p class="text-xs text-green-900">
                💡 <strong>AI Recommendation:</strong> Based on demand forecasts, consider 
                increasing driver incentives during peak hours (6-9 AM, 6-9 PM) to improve acceptance rates.
                Current wait times are acceptable; monitor demand in Downtown area closely.
            </p>
        </section>
    </div>
</x-filament-panels::page>
